sudo: false

language: node_js

node_js:
  - "12"

cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
  - pnpm run build

script:
  - pnpm run test