[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
from = "examples/vue2/dist"
to = "project-1.netlify.app/:splat"
status = 200
force = true

from = "examples/react15/dist"
to = "react15.netlify.app/:splat"
status = 200
force = true

from = "examples/react16/dist"
to = "react16.netlify.app/:splat"
status = 200
force = true